version: '3'
services:
  ejabberd:
    image: ghcr.io/processone/ejabberd:latest
    ports:
      - "1883:1883"
      - "5222:5222"
      - "5280:5280"
      - "5269:5269"
      - "5443:5443"
      - "4369-4399:4369-4399"
    volumes:
      - ./conf:/opt/ejabberd/conf
      - ./database:/opt/ejabberd/database/
      - ./logs:/opt/ejabberd/logs/
      - ./upload:/opt/ejabberd/upload/
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: services
      MYSQL_USER: services
      MYSQL_PASSWORD: services